INSERT INTO DDDQ_Top2000.dbo.ARTIST (ARTIST_NAME, ARTIST_TYPE)
SELECT artist_name as ARTIST_NAME, 'person' as ARTIST_TYPE
FROM Top2000_cleaned.dbo.Artist
GO

INSERT INTO DDDQ_Top2000.dbo.SONG (ARTIST_NAME, SONG_NAME, RELEASE_YEAR, DURATION)
SELECT artist as ARTIST_NAME, titel as SONG_NAME, release_year as RELEASE_YEAR, duration as DURATION
FROM Top2000_cleaned.dbo.Song
GO

INSERT INTO DDDQ_Top2000.dbo.FEATURINGARTISTOFSONG (SONG_NAME, SONG_ARTIST_NAME, ARTIST_NAME)
SELECT song_titel as SONG_NAME, artist as SON_ARTIST_NAME, featured_artist as ARTIST_NAME
FROM Top2000_cleaned.dbo.SongFeaturedArtist
GO

INSERT INTO DDDQ_Top2000.dbo.TOP2000LIST (EDITION_YEAR)
SELECT DISTINCT edition_year
FROM Top2000_cleaned.dbo.Top2000Lijst
GO

INSERT INTO DDDQ_Top2000.dbo.TOP2000LISTENTRY (ARTIST_NAME, SONG_NAME, EDITION_YEAR, POSITION)
SELECT artist as ARTIST_NAME, titel as SONG_NAME, edition_year as EDITION_YEAR, position as POSITION
FROM Top2000_cleaned.dbo.Top2000Lijst
GO

INSERT INTO DDDQ_Top2000.dbo.GENRE (GENRE_NAME)
SELECT genre_name as GENRE_NAME
FROM Top2000_cleaned.dbo.Genre
GO

INSERT INTO DDDQ_Top2000.dbo.GENREOFSONG (GENRE_NAME, ARTIST_NAME, SONG_NAME)
SELECT genre as GENRE_NAME, artist as ARTIST_NAME, titel as SONG_NAME
FROM Top2000_cleaned.dbo.SongGenre
GO

INSERT INTO DDDQ_Top2000.dbo.ARTIST (ARTIST_NAME, ARTIST_TYPE)
SELECT componist_name as ARTIST_NAME, 'person' as ARTIST_TYPE
FROM Top2000_cleaned.dbo.Componist
LEFT JOIN DDDQ_Top2000.dbo.ARTIST AS ARTIST ON ARTIST.ARTIST_NAME = componist_name
WHERE ARTIST.ARTIST_NAME IS NULL
GO

INSERT INTO DDDQ_Top2000.dbo.PERSON (ARTIST_NAME, PERSON_NAME, BIRTH_DATE)
SELECT componist_name as ARTIST_NAME, componist_name as PERSON_NAME, '01-01-1999' as BIRTH_DATE
FROM Top2000_cleaned.dbo.Componist
GO

INSERT INTO DDDQ_Top2000.dbo.COMPOSEROFSONG (SONG_ARTIST_NAME, SONG_NAME, ARTIST_NAME)
SELECT artist as SON_ARTIST_NAME, titel as SONG_NAME, componist_name as ARTIST_NAME
FROM Top2000_cleaned.dbo.SongComponist
GO

UPDATE A
SET ARTIST_TYPE = 'band'
FROM DDDQ_Top2000.dbo.ARTIST A
JOIN (
	SELECT ARTIST.*
	FROM DDDQ_Top2000.dbo.ARTIST as ARTIST
	INNER JOIN Top2000_cleaned.dbo.ampersand_artists as ampersand_artists ON ampersand_artists.artist_name = ARTIST.ARTIST_NAME
) sub ON A.ARTIST_NAME = sub.artist_name AND A.ARTIST_TYPE = sub.ARTIST_TYPE
GO
